const programs = {
  'DEV-F': {
    code: 'DEV-F',
    level: 'L1',
    order: 1,
    icon: 'image/python.png',
    title: 'Developer Foundation',
    target: 'Người mới · Sinh viên CNTT · Chuyển ngành',
    duration: '5 buổi',
    role: 'Python Developer Foundation',
    badge: '🔥 Nền tảng',
    description: 'Trang bị nền tảng lập trình vững chắc với Python, PostgreSQL và Git — đủ để bắt đầu học Odoo.',
    outcome: [
      'Python cơ bản',
      'SQL & Database',
      'Git & làm việc nhóm',
      'Mini Project: Customer Management',
    ],
    sessions: [
      {
        num: 1,
        title: 'Định hướng & Môi trường phát triển',
        topics: [
          'Giới thiệu nghề Developer',
          'Quy trình phát triển phần mềm',
          'Cài đặt Python & PyCharm',
          'Git & GitHub',
          'Virtual Environment',
          'Chạy chương trình Python đầu tiên',
        ],
        project: 'Hoàn thiện môi trường phát triển',
      },
      {
        num: 2,
        title: 'Python Fundamentals',
        topics: [
          'Biến, Kiểu dữ liệu',
          'Toán tử',
          'Điều kiện (if/elif/else)',
          'Vòng lặp (for, while)',
          'List, Tuple, Dictionary, Set',
        ],
        project: 'Quản lý danh sách học viên',
      },
      {
        num: 3,
        title: 'Function & OOP',
        topics: [
          'Function, Module, Package',
          'Class, Object',
          'Inheritance',
          'Exception',
        ],
        project: 'Student, Teacher, Course',
      },
      {
        num: 4,
        title: 'PostgreSQL & Git',
        topics: [
          'Database, Table',
          'SQL cơ bản (CRUD)',
          'JOIN',
          'Git Workflow, Branch, Merge',
        ],
        project: 'Thiết kế database quản lý học viên + Làm việc nhóm với Git',
      },
      {
        num: 5,
        title: 'Mini Project — Customer Management',
        topics: [
          'Xây dựng ứng dụng Customer Management',
          'Python + OOP + PostgreSQL + Git',
        ],
        project: 'Hoàn thiện ứng dụng và đưa lên GitHub',
      },
    ],
  },

  'ODO-F': {
    code: 'ODO-F',
    level: 'L2',
    order: 2,
    icon: 'image/odoo.png',
    title: 'Odoo Developer Foundation',
    target: 'Đã có nền tảng lập trình',
    duration: '8 buổi',
    role: 'Junior Odoo Developer',
    badge: '🔥 Cốt lõi',
    description: 'Tự phát triển và customize module Odoo — từ kiến trúc đến triển khai. Dự án xuyên suốt: Training Management System.',
    outcome: [
      'Hiểu kiến trúc Odoo',
      'Viết module theo chuẩn',
      'Security & Report PDF',
      'Website & Portal',
      'Portfolio: Training Management System',
    ],
    sessions: [
      {
        num: 1,
        title: 'Kiến trúc Odoo',
        topics: [
          'Odoo Framework & MVC Pattern',
          'ORM',
          'Module Structure & Addons Path',
          'Manifest',
          'Cài đặt Source Code',
        ],
        project: 'Hello Module',
      },
      {
        num: 2,
        title: 'ORM & Models',
        topics: [
          'Models',
          'Fields (Char, Text, Integer, Float, Boolean, Date, Datetime, Selection)',
          'Sequence',
          'Chatter & Mail Thread',
        ],
        project: 'Student Management',
      },
      {
        num: 3,
        title: 'Quan hệ dữ liệu',
        topics: [
          'Many2one',
          'One2many',
          'Many2many',
          'Related Fields',
          'Compute Fields',
          'Onchange',
        ],
        project: 'Student, Course, Teacher',
      },
      {
        num: 4,
        title: 'Views',
        topics: [
          'Tree View',
          'Form View',
          'Search View',
          'Kanban View',
          'Notebook',
          'Smart Button',
        ],
        project: 'Quản lý khóa học',
      },
      {
        num: 5,
        title: 'Business Logic',
        topics: [
          'Constraint (Python)',
          'SQL Constraint',
          'Action (ir.actions)',
          'Menu & Wizard',
          'Server Action',
        ],
        project: 'Enrollment',
      },
      {
        num: 6,
        title: 'Security & Report',
        topics: [
          'Groups',
          'ACL (Access Control List)',
          'Record Rule',
          'QWeb PDF Report',
          'Email Template',
        ],
        project: 'Certificate',
      },
      {
        num: 7,
        title: 'Controller & Website',
        topics: [
          'Controller',
          'Website & Portal',
          'HTTP Route',
          'JSON API',
        ],
        project: 'Website khóa học',
      },
      {
        num: 8,
        title: 'Final Project — Training Management System',
        topics: [
          'Student, Teacher, Course, Class',
          'Enrollment, Schedule, Attendance',
          'Report',
        ],
        project: 'Hoàn thiện Training Management System',
      },
    ],
  },

  'AI-O': {
    code: 'AI-O',
    level: 'L3',
    order: 3,
    icon: 'image/odoo.png',
    title: 'AI & Vibe Coding Odoo',
    target: 'Đã biết Odoo — muốn tăng năng suất',
    duration: '5 buổi',
    role: 'AI-Enhanced Odoo Developer',
    badge: '✨ AI',
    description: 'Tăng tốc phát triển Odoo 2-5 lần bằng AI — từ prompt engineering đến phát triển module hoàn chỉnh.',
    outcome: [
      'Sử dụng AI để phát triển Odoo',
      'Tăng tốc phát triển 2-5 lần',
      'Review & Refactor Code với AI',
      'AI Project: Module Odoo hoàn chỉnh',
    ],
    sessions: [
      {
        num: 1,
        title: 'AI Prompt Engineering',
        topics: [
          'ChatGPT, Claude, Gemini',
          'Prompt Template',
          'Prompt tối ưu cho Odoo',
        ],
        project: '',
      },
      {
        num: 2,
        title: 'AI Pair Programming',
        topics: [
          'Cursor',
          'Claude Code',
          'OpenCode',
          'GitHub Copilot',
        ],
        project: 'Sinh module Odoo bằng AI',
      },
      {
        num: 3,
        title: 'AI Review & Debug',
        topics: [
          'Code Review với AI',
          'Refactor',
          'Debug',
          'Performance',
          'Security',
        ],
        project: '',
      },
      {
        num: 4,
        title: 'AI Technical Design',
        topics: [
          'AI hỗ trợ BRD, Flow',
          'Database Design',
          'API Design',
          'Documentation',
          'Test Case',
        ],
        project: '',
      },
      {
        num: 5,
        title: 'AI Project',
        topics: [
          'Phát triển hoàn chỉnh module Odoo bằng AI',
          'Phân tích yêu cầu → Viết mã → Kiểm thử → Tài liệu hóa',
        ],
        project: 'Module Odoo hoàn chỉnh',
      },
    ],
  },

  'ODO-B': {
    code: 'ODO-B',
    level: 'L4',
    order: 4,
    icon: 'image/postgresql.jpg',
    title: 'Odoo Business & Functional',
    target: 'Developer · BA · Functional Consultant · PM · Solution Consultant',
    duration: '8 buổi',
    role: 'BA / Functional Consultant',
    badge: 'Nghiệp vụ',
    description: 'Hiểu quy trình vận hành doanh nghiệp trên Odoo, phân tích yêu cầu, thiết kế giải pháp và viết tài liệu triển khai.',
    outcome: [
      'Hiểu quy trình vận hành doanh nghiệp trên Odoo',
      'Khảo sát & phân tích yêu cầu khách hàng',
      'Viết tài liệu BRD, FRD, SRS',
      'Mapping nghiệp vụ vào Odoo Standard',
      'Gap Analysis & Scope Estimate',
    ],
    sessions: [
      {
        num: 1,
        title: 'Tổng quan ERP & Odoo',
        topics: [
          'ERP là gì? Kiến trúc Odoo',
          'Chu trình triển khai ERP',
          'Master Data & Business Process',
          'Phân quyền người dùng',
        ],
        project: 'Phân tích quy trình doanh nghiệp SME',
      },
      {
        num: 2,
        title: 'CRM & Sales',
        topics: [
          'Lead, Opportunity',
          'Quotation, Sale Order',
          'Invoice, Payment',
        ],
        project: 'Quy trình bán hàng từ Lead đến thu tiền',
      },
      {
        num: 3,
        title: 'Purchase & Inventory',
        topics: [
          'Purchase Request, RFQ, Purchase Order',
          'Receipt, Stock, Delivery',
          'Inventory Adjustment',
        ],
        project: 'Quy trình mua hàng & quản lý kho',
      },
      {
        num: 4,
        title: 'Accounting Workflow',
        topics: [
          'Accounting Workflow',
          'Journal Entries',
          'Invoices & Payments',
          'Reconciliation & Tax',
        ],
        project: 'Hạch toán doanh thu — chi phí trên Odoo',
      },
      {
        num: 5,
        title: 'HR & Project Management',
        topics: [
          'HR: Recruitment, Attendance, Leave, Payroll',
          'Project: Project, Timesheet',
        ],
        project: 'Quản lý nhân sự & chi phí dự án',
      },
      {
        num: 6,
        title: 'Business Analysis',
        topics: [
          'Requirement Gathering & Interview',
          'User Story, Use Case',
          'Business Flow, BPMN',
          'Gap Analysis',
        ],
        project: 'Phân tích yêu cầu khách hàng',
      },
      {
        num: 7,
        title: 'Functional Consultant & Documentation',
        topics: [
          'Mapping Requirement → Odoo',
          'Standard hay Customize?',
          'Scope, Estimate, Change Request, UAT',
          'BRD, FRD, SRS, Workflow, ERD',
        ],
        project: 'Viết tài liệu triển khai',
      },
      {
        num: 8,
        title: 'Final Project',
        topics: [
          'Phân tích & thiết kế hệ thống cho doanh nghiệp thực tế',
          'Business Flow, ERD, BRD, Module List, Roadmap',
        ],
        project: 'Trình bày giải pháp cho doanh nghiệp',
      },
    ],
  },

  'ODO-A': {
    code: 'ODO-A',
    level: 'L5',
    order: 5,
    icon: 'image/odoo.png',
    title: 'Odoo Advanced Developer',
    target: 'Odoo Developer có từ 6 tháng kinh nghiệm',
    duration: '8 buổi',
    role: 'Senior Odoo Developer',
    badge: 'Chuyên sâu',
    description: 'Làm chủ Odoo Framework — tối ưu hiệu năng, tích hợp hệ thống, phát triển dự án Enterprise quy mô lớn.',
    outcome: [
      'Advanced ORM & SQL Optimization',
      'API Integration (XMLRPC, REST, Webhook)',
      'OWL Framework & POS',
      'Queue Job, Cron, Scheduler',
      'Performance & Security',
      'Unit Test & CI',
    ],
    sessions: [
      {
        num: 1,
        title: 'Advanced ORM',
        topics: [
          'ORM Internals',
          'Environment & Cache',
          'Prefetch',
          'SQL Optimization',
        ],
        project: '',
      },
      {
        num: 2,
        title: 'Advanced Business Logic',
        topics: [
          'Decorator (@api.depends, @api.onchange, @api.constrains)',
          'Compute + Inverse',
          'Context',
          'Company Rules (Multi-Company)',
        ],
        project: '',
      },
      {
        num: 3,
        title: 'Integration',
        topics: [
          'XMLRPC, JSONRPC',
          'REST API',
          'Webhook',
          'OAuth',
        ],
        project: '',
      },
      {
        num: 4,
        title: 'Queue & Automation',
        topics: [
          'Cron Job',
          'Queue Job',
          'Background Task',
          'Scheduler',
        ],
        project: '',
      },
      {
        num: 5,
        title: 'OWL Framework',
        topics: [
          'Component, Hook, Service',
          'POS',
          'Frontend Extension',
        ],
        project: '',
      },
      {
        num: 6,
        title: 'Performance & Security',
        topics: [
          'Performance Profiling',
          'Debug Tools',
          'SQL Injection & XSS Prevention',
          'Security Best Practices',
        ],
        project: '',
      },
      {
        num: 7,
        title: 'Testing',
        topics: [
          'Unit Test (TransactionCase)',
          'Integration Test (HttpCase)',
          'Mock',
          'CI Integration',
        ],
        project: '',
      },
      {
        num: 8,
        title: 'Final Project',
        topics: [
          'HR Management hoặc CRM Enterprise',
        ],
        project: 'Dự án Enterprise hoàn chỉnh',
      },
    ],
  },

  'ODO-D': {
    code: 'ODO-D',
    level: 'L6',
    order: 6,
    icon: 'image/devops.jpg',
    title: 'DevOps for Odoo',
    target: 'Odoo Developer · Technical Consultant · System Admin',
    duration: '5 buổi',
    role: 'DevOps Engineer / Technical Consultant',
    badge: 'Triển khai',
    description: 'Triển khai và vận hành hệ thống Odoo Production — từ Docker, Nginx đến CI/CD và Monitoring.',
    outcome: [
      'Production Server',
      'Docker & Docker Compose',
      'Nginx & SSL Let\'s Encrypt',
      'Backup & Monitoring',
      'CI/CD (GitLab CI, GitHub Actions)',
    ],
    sessions: [
      {
        num: 1,
        title: 'Linux & Docker',
        topics: [
          'Ubuntu & Linux Command',
          'Docker & Docker Compose',
          'PostgreSQL',
        ],
        project: 'Deploy Odoo Local',
      },
      {
        num: 2,
        title: 'Nginx & SSL',
        topics: [
          'Reverse Proxy',
          'Domain & HTTPS',
          'Let\'s Encrypt',
          'Security',
        ],
        project: 'Deploy Production',
      },
      {
        num: 3,
        title: 'Backup & Monitoring',
        topics: [
          'Backup Database & Filestore',
          'Restore',
          'Monitoring & Log',
          'Telegram Alert',
        ],
        project: 'Tự động Backup',
      },
      {
        num: 4,
        title: 'CI/CD',
        topics: [
          'GitLab CI',
          'GitHub Actions',
          'Auto Deploy',
          'Migration & Versioning',
        ],
        project: 'Deploy tự động',
      },
      {
        num: 5,
        title: 'Production Project',
        topics: [
          'Triển khai hoàn chỉnh: Odoo + PostgreSQL + Nginx + SSL + Docker',
          'Backup + Monitoring + CI/CD',
        ],
        project: 'Production Server hoàn chỉnh',
      },
    ],
  },
};
